title: PROGRAMMING REVIEW
logo: /assets/img/logo.png
description: Slow catching up the latest programming trends.
lang: en
theme: minima
footer: © PROGRAMMING REVIEW 2010-2020
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
build_revision: 21
excerpt_separator: [[[]]]
# plugins:
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-feed
