title: PROGRAMMING REVIEW
logo: /assets/img/logo.png
description: Slow catching up the latest programming trends.
lang: en
theme: minima
footer: © PROGRAMMING REVIEW 2010-2020
highlighter: rouge
plugins:
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
