title: PROGRAMMING REVIEW
logo: /assets/img/logo.png
description: Slow catching up the latest programming trends.
lang: en
theme: minima
plugins:
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
